version: "3.7"
services:
  hub:
    image: seleniarm/hub:4.10
    ports:
      - 4444:4444
  chrome:
    image: seleniarm/node-chromium
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: seleniarm/node-firefox
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
        replicas: 4
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
      - SE_VNC_NO_PASSWORD=1